#!/bin/bash

SESSION='Main'

tmux -2 new-session -d -s $SESSION

tmux rename-window -t $SESSION:1 'Coding'
tmux selectp -t 1              # Select pane 0
tmux splitw -v -p 85 	  # Split pane 0 vertically by 50%
tmux selectp -t 1              # Select pane 0
tmux splitw -h -p 15
tmux selectp -t 1              # Select pane 0
tmux splitw -h -p 45 
tmux selectp -t 4              # Select pane 1
tmux splitw -h -p 33           # Split pane 1 horizontally by 25%
tmux splitw -v -p 50

tmux send-keys -t "3" C-z 'tty-clock' Enter
tmux send-keys -t "6" C-z 'htop' Enter
tmux send-keys -t "5" C-z 'ipython' Enter
tmux send-keys -t "4" C-z 'vim' Enter
tmux send-keys -t "2" C-z 'while true; do cdf | grep /dev/sd ; sleep 10; clear ; done; ' Enter
tmux selectp -t 2
tmux splitw -v -p 50
tmux send-keys -t "3" C-z 'while true; do meteo USMA0046 ; cat /tmp/conky_meteo.txt ; sleep 900 ; clear ; done; ' Enter
tmux selectp -t 5

tmux new-window -t $SESSION:2 -n 'Odyssey'
tmux select-window -t $SESSION:2
tmux splitw -h 
tmux selectp -t 2
tmux splitw -v -p 85
tmux selectp -t 2
tmux splitw -h -p 30

tmux send-keys -t "3" C-z 'Odyssey' Enter
sleep 10
tmux send-keys -t "2" C-z 'ssh Odyssey' Enter
sleep 3 
tmux send-keys -t "2" C-z 'while true; do clear ; sacct ; sleep 10 ; done; ' Enter
tmux send-keys -t "1" C-z 'ssh Odyssey' Enter
tmux send-keys -t "4" C-z 'ssh Odyssey' Enter
tmux selectp -t 3
tmux clock-mode

tmux selectp -t 1
tmux select-window -t $SESSION:1

tmux -2 attach-session -t $SESSION
